services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data   # 👈 ADD THIS

  odoo:
    image: odoo:19
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - ./:/mnt/extra-addons              # 👈 BETTER
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  pgdata:                                # 👈 ADD THIS
